### ISSUE TITLE
Switch out mail library (again)

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-mail-service#118]
https://github.com/Shopify/gomail has been archived and is no longer being maintained.

We should see about switching to another library or implementation.

Possible candidates:

- https://github.com/xhit/go-simple-mail from @xhit
- https://github.com/wneessen/go-mail from @wneessen

Thanks to @Neustradamus for the heads up.

**Comment by Neustradamus** [comment]
@Jumpy-Squirrel: Thanks for your answer and this new ticket!
- https://github.com/eurofurence/reg-mail-service/issues/52

For information, Gitea has recently migrated to:
- https://github.com/wneessen/go-mail from @wneessen
