### ISSUE TITLE
replace abandoned mail library

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-mail-service#52]
https://github.com/go-gomail/gomail/issues/182

Our mail library is abandonware, and it currently only supports attachments from files, but we want to store base64 encoded attachments in the database / expose via API.

~~One possible alternative might be https://github.com/xhit/go-simple-mail~~

~~We will have to ensure to maintain backwards compatibility, maybe temporarily import both libraries.~~

Update:

There's now a maintained fork for our original library that also supports attachments from writers in-memory. Should cause fewer code changes. https://github.com/Shopify/gomail 

We should try that first.

**Comment by Neustradamus** [comment]
@ItsSelis, @Jumpy-Squirrel: It is possible to change it?
- https://github.com/Shopify/gomail

It has been archived and there is a vulnerability:
- https://github.com/Shopify/gomail
- https://github.com/Shopify/gomail/issues/59

There are:
- https://github.com/xhit/go-simple-mail from @xhit
- https://github.com/wneessen/go-mail from @wneessen

Linked to:
- https://github.com/eurofurence/reg-mail-service/pull/61
